[package]
name = "calc"
version = "0.1.0"
authors = ["FeÌlix Saparelli <felix@passcod.name>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.79"
rhai = "0.19.0"

[build-dependencies]
cbindgen = "0.15.0"
